import { LedgerGroup } from '@shared/entity/accounting/ledger-group';
import { defalutLedgerGroupNames as dlgn} from '@shared/util/ledger-group-names';
export const defaultLedgerGroups:Array<LedgerGroup> = [
  {name: 'Assets'},
  {name: 'Liabilities'},
  {name: 'Expenses'},
  {name: 'Income'},
  {name: 'Branch / Divisions',
    parent: {name: 'Liabilities'}},
  {name: 'Capital Account',
    parent: {name: 'Liabilities'}},
  {name: 'Reserves & Surplus',
    parent: {name: 'Capital Account'}},
  {name: 'Current Assets',
    parent: {name: 'Assets'}},
  {name: dlgn.BANK_ACCOUNTS,
    parent: {name: 'Current Assets'}},
  {name: dlgn.CACH_IN_HAND,
    parent: {name: 'Current Assets'}},
  {name: 'Loans and Advances - Asset',
    parent: {name: 'Current Assets'}},
  {name: 'Deposits - Asset',
    parent: {name: 'Current Assets'}},
  {name: 'Loans and Advances - Asset',
    parent: {name: 'Current Assets'}},
  {name: 'Stock-in-hand',
    parent: {name: 'Current Assets'}},
  {name: dlgn.SUNDRY_DEBTORS,
    parent: {name: 'Current Assets'}},
  {name: 'Current Liabilities',
    parent: {name: 'Liabilities'}},
  {name: 'Duties and Taxes',
    parent: {name: 'Current Liabilities'}},
  {name: 'Provisions',
    parent: {name: 'Current Liabilities'}},
  {name: dlgn.SUNDRY_CREDITORS,
    parent: {name: 'Current Liabilities'}},
  {name: 'Direct Expenses',
    parent: {name: 'Expenses'}},
  {name: 'Direct Income',
    parent: {name: 'Income'}},
  {name: 'Fixed Assets',
    parent: {name: 'Assets'}},
  {name: 'Indirect Expenses',
    parent: {name: 'Expenses'}},
  {name: 'Indirect Income',
    parent: {name: 'Income'}},
  {name: 'Investments',
    parent: {name: 'Assets'}},
  {name: 'Loans - Liability',
    parent: {name: 'Liabilities'}},
  {name: 'Bank OD Accounts',
    parent: {name: 'Loans - Liability'}},
  {name: 'Secured Loans',
    parent: {name: 'Loans - Liability'}},
  {name: 'Unsecured Loans',
    parent: {name: 'Loans - Liability'}},
  {name: 'Misc. Expenses - Asset',
    parent: {name: 'Assets'}},
  {name: dlgn.PURCHASE_ACCOUNTS,
    parent: {name: 'Expenses'}},
  {name: dlgn.SALES_ACCOUNTS,
    parent: {name: 'Income'}},
  {name: 'Suspense Accounts',
    parent: {name: 'Liabilities'}},

];
