import { LedgerGroup } from '@shared/entity/accounting/ledger-group';
import { defalutLedgerGroupCodes as dlgn} from '@shared/util/ledger-group-codes';
const extras = {
  'gstin': {'type': 'string',
    'name': 'GSTIN/UIN'},
  'state': {'type': 'string',
    'name': 'State'},
  'mobile': {'type': 'string',
    'name': 'Mobile'},
  'email': {'type': 'string',
    'name': 'E-Mail'},
  'address1': {'type': 'string',
    'name': 'Address Line 1'},
  'address2': {'type': 'string',
    'name': 'Address Line 2'},
  'address3': {'type': 'string',
    'name': 'Address Line 3'},
  'pincode': {'type': 'string',
    'name': 'PIN Code'}
};
export const defaultLedgerGroups:Array<LedgerGroup> = [
  {name: 'Assets',
    code: dlgn.ASSETS},
  {name: 'Liabilities',
    code: dlgn.LIABILITIES},
  {name: 'Expenses',
    code: dlgn.EXPENSES},
  {name: 'Income',
    code: dlgn.INCOME},
  {name: 'Branch / Divisions',
    code: dlgn.BRANCH_DIVISIONS,
    parent: {code: dlgn.LIABILITIES}},
  {name: 'Capital Account',
    code: dlgn.CAPITAL_ACCOUNT,
    parent: {code: dlgn.LIABILITIES}},
  {name: 'Reserves & Surplus',
    code: dlgn.RESERVES_SURPLUS,
    parent: {code: dlgn.CAPITAL_ACCOUNT}},
  {name: 'Current Assets',
    code: dlgn.CURRENT_ASSETS,
    parent: {code: dlgn.ASSETS}},
  {name: 'Bank Accounts',
    code: dlgn.BANK_ACCOUNTS,
    parent: {code: dlgn.CURRENT_ASSETS}},
  {name: 'Cash in Hand',
    code: dlgn.CACH_IN_HAND,
    parent: {code: dlgn.CURRENT_ASSETS}},
  {name: 'Loans and Advances - Asset',
    code: dlgn.LOANS_ADVANCES_ASSET,
    parent: {code: dlgn.CURRENT_ASSETS}},
  {name: 'Deposits - Asset',
    code: dlgn.DEPOSITS_ASSET,
    parent: {code: dlgn.CURRENT_ASSETS}},
  {name: 'Stock-in-hand',
    code: dlgn.STOCK_IN_HAND,
    parent: {code: dlgn.CURRENT_ASSETS}},
  {name: 'Sundry Debtors',
    code: dlgn.SUNDRY_DEBTORS,
    parent: {code: dlgn.CURRENT_ASSETS},
    extras},
  {name: 'Current Liabilities',
    code: dlgn.CURRENT_LIABILITIES,
    parent: {code: dlgn.LIABILITIES}},
  {name: 'Duties and Taxes',
    code: dlgn.DUTIES_AND_TAXES,
    parent: {code: dlgn.CURRENT_LIABILITIES}},
  {name: 'Provisions',
    code: dlgn.PROVISIONS,
    parent: {code: dlgn.CURRENT_LIABILITIES}},
  {name: 'Sundry Creditors',
    code: dlgn.SUNDRY_CREDITORS,
    parent: {code: dlgn.CURRENT_LIABILITIES},
    extras},
  {name: 'Direct Expenses',
    code: dlgn.DIRECT_EXPENSES,
    parent: {code: dlgn.EXPENSES}},
  {name: 'Direct Income',
    code: dlgn.DIRECT_INCOME,
    parent: {code: dlgn.INCOME}},
  {name: 'Fixed Assets',
    code: dlgn.FIXED_ASSETS,
    parent: {code: dlgn.ASSETS}},
  {name: 'Indirect Expenses',
    code: dlgn.INDIRECT_EXPENSES,
    parent: {code: dlgn.EXPENSES}},
  {name: 'Indirect Income',
    code: dlgn.INDIRECT_INCOME,
    parent: {code: dlgn.INCOME}},
  {name: 'Investments',
    code: dlgn.INVESTMENTS,
    parent: {code: dlgn.ASSETS}},
  {name: 'Loans - Liability',
    code: dlgn.LOANS_LIABILITY,
    parent: {code: dlgn.LIABILITIES}},
  {name: 'Bank OD Accounts',
    code: dlgn.BANK_OD_ACCOUNTS,
    parent: {code: dlgn.LOANS_LIABILITY}},
  {name: 'Secured Loans',
    code: dlgn.SECURED_LOANS,
    parent: {code: dlgn.LOANS_LIABILITY}},
  {name: 'Unsecured Loans',
    code: dlgn.UNSECURED_LOANS,
    parent: {code: dlgn.LOANS_LIABILITY}},
  {name: 'Misc. Expenses - Asset',
    code: dlgn.MISC_EXPENSES_ASSET,
    parent: {code: dlgn.ASSETS}},
  {name: 'Purchase Accounts',
    code: dlgn.PURCHASE_ACCOUNTS,
    parent: {code: dlgn.EXPENSES}},
  {name: 'Sales Accounts',
    code: dlgn.SALES_ACCOUNTS,
    parent: {code: dlgn.INCOME}},
  {name: 'Suspense Accounts',
    code: dlgn.SUSPENSE_ACCOUNTS,
    parent: {code: dlgn.LIABILITIES}},

];
